version: "3.7"
services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"
    volumes:
      # Server data
      - ./data:/home/${USER}/Zomboid
      # Workshop mods folder
      - ./workshop-mods:/app/steamapps/workshop